openapi: 3.0.1
info:
  title: Gestion Materiel API
  version: '1.0'
paths:
  /api/v1/quotes:
    get:
      summary: List quotes
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/Quote'
    post:
      summary: Create quote
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/Quote'
      responses:
        '201':
          description: Created
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Quote'
  /api/v1/orders:
    get:
      summary: List orders
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/Order'
    post:
      summary: Create order
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/Order'
      responses:
        '201':
          description: Created
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Order'
  /api/v1/resources:
    get:
      summary: List resources
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/Resource'
    post:
      summary: Create resource
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/Resource'
      responses:
        '201':
          description: Created
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Resource'
  /api/v1/resources/{id}:
    put:
      summary: Update resource
      parameters:
        - name: id
          in: path
          required: true
          schema:
            type: string
            format: uuid
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/Resource'
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Resource'
    delete:
      summary: Delete resource
      parameters:
        - name: id
          in: path
          required: true
          schema:
            type: string
            format: uuid
      responses:
        '204':
          description: Deleted
  /api/v1/resource-types:
    get:
      summary: List resource types
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/ResourceType'
    post:
      summary: Create resource type
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/ResourceType'
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ResourceType'
  /api/v1/resource-types/{code}:
    put:
      summary: Update resource type
      parameters:
        - name: code
          in: path
          required: true
          schema:
            type: string
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/ResourceType'
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ResourceType'
    delete:
      summary: Delete resource type
      parameters:
        - name: code
          in: path
          required: true
          schema:
            type: string
      responses:
        '204':
          description: Deleted
  /api/v1/resources/{id}/unavailability:
    get:
      summary: List resource unavailability periods
      parameters:
        - name: id
          in: path
          required: true
          schema:
            type: string
            format: uuid
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/Unavailability'
    post:
      summary: Add unavailability period
      parameters:
        - name: id
          in: path
          required: true
          schema:
            type: string
            format: uuid
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/Unavailability'
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Unavailability'
  /api/v1/resources/{id}/unavailability/{uid}:
    delete:
      summary: Remove unavailability period
      parameters:
        - name: id
          in: path
          required: true
          schema:
            type: string
            format: uuid
        - name: uid
          in: path
          required: true
          schema:
            type: string
            format: uuid
      responses:
        '204':
          description: Deleted
components:
  schemas:
    DocumentLine:
      type: object
      properties:
        designation:
          type: string
        quantite:
          type: number
        prixUnitaireHT:
          type: number
        remisePct:
          type: number
        tvaPct:
          type: number
    Quote:
      type: object
      properties:
        id:
          type: string
          format: uuid
        number:
          type: string
        lines:
          type: array
          items:
            $ref: '#/components/schemas/DocumentLine'
        totalHT:
          type: number
          format: double
    Order:
      type: object
      properties:
        id:
          type: string
          format: uuid
        number:
          type: string
        lines:
          type: array
          items:
            $ref: '#/components/schemas/DocumentLine'
        totalHT:
          type: number
          format: double
    InterventionResourceRef:
      type: object
      properties:
        id:
          type: string
          format: uuid
        name:
          type: string
        icon:
          type: string
          description: "Icône simple (emoji, caractère)"
    Resource:
      type: object
      properties:
        id:
          type: string
          format: uuid
        name:
          type: string
        type:
          $ref: '#/components/schemas/ResourceType'
        color:
          type: string
        notes:
          type: string
        capacity:
          type: integer
        tags:
          type: string
        weeklyUnavailability:
          type: string
        unavailabilities:
          type: array
          items:
            $ref: '#/components/schemas/Unavailability'
    Intervention:
      type: object
      properties:
        id:
          type: string
          format: uuid
        resourceId:
          type: string
          format: uuid
          description: "Ressource principale (compatibilité)"
        resources:
          type: array
          items:
            $ref: '#/components/schemas/InterventionResourceRef'
        clientName:
          type: string
        siteLabel:
          type: string
        craneName:
          type: string
        truckName:
          type: string
        driverName:
          type: string
        agency:
          type: string
        status:
          type: string
        favorite:
          type: boolean
        quoteNumber:
          type: string
        orderNumber:
          type: string
        deliveryNumber:
          type: string
        invoiceNumber:
          type: string
        color:
          type: string
        locked:
          type: boolean
        dateHeureDebut:
          type: string
          format: date-time
        dateHeureFin:
          type: string
          format: date-time
    ResourceType:
      type: object
      required: [code]
      properties:
        code:
          type: string
        label:
          type: string
        icon:
          type: string
    Unavailability:
      type: object
      required: [start, end]
      properties:
        id:
          type: string
          format: uuid
        start:
          type: string
          format: date-time
        end:
          type: string
          format: date-time
        reason:
          type: string
