package com.materiel.suite.client.model;

import java.math.BigDecimal;

/** Ligne de pré-devis liée à une intervention. */
public class BillingLine {
  private String id;
  private String resourceId;
  private String designation;
  private BigDecimal quantity = BigDecimal.ONE;
  private String unit = "u";
  private BigDecimal unitPriceHt = BigDecimal.ZERO;
  private BigDecimal totalHt = BigDecimal.ZERO;
  private boolean autoGenerated;

  public String getId(){ return id; }
  public void setId(String id){ this.id = id; }
  public String getResourceId(){ return resourceId; }
  public void setResourceId(String resourceId){ this.resourceId = resourceId; }
  public String getDesignation(){ return designation; }
  public void setDesignation(String designation){ this.designation = designation; }
  public BigDecimal getQuantity(){ return quantity; }
  public void setQuantity(BigDecimal quantity){ this.quantity = quantity; }
  public String getUnit(){ return unit; }
  public void setUnit(String unit){ this.unit = unit; }
  public BigDecimal getUnitPriceHt(){ return unitPriceHt; }
  public void setUnitPriceHt(BigDecimal unitPriceHt){ this.unitPriceHt = unitPriceHt; }
  public BigDecimal getTotalHt(){ return totalHt; }
  public void setTotalHt(BigDecimal totalHt){ this.totalHt = totalHt; }
  public boolean isAutoGenerated(){ return autoGenerated; }
  public void setAutoGenerated(boolean autoGenerated){ this.autoGenerated = autoGenerated; }
}
